# Generated by Django 5.0.6 on 2024-06-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chatting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='txt',
            new_name='value',
        ),
    ]
